// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoTKhoZvyDcNZp9V16EPbf--pvDRrzpyw',
    appId: '1:838888207729:web:89ea1ed171a0ca5eb7b2d0',
    messagingSenderId: '838888207729',
    projectId: 'quickserve-194d8',
    authDomain: 'quickserve-194d8.firebaseapp.com',
    storageBucket: 'quickserve-194d8.firebasestorage.app',
    measurementId: 'G-ER08HW20T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu79-KAL642btKzTyLq8rnoFaUY2XXmMc',
    appId: '1:838888207729:android:c5e3fc8e02776b65b7b2d0',
    messagingSenderId: '838888207729',
    projectId: 'quickserve-194d8',
    storageBucket: 'quickserve-194d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASZzmu9ZS_sr30hGrfs8d4E__RdsFMi54',
    appId: '1:838888207729:ios:d0ba194a5d2aade1b7b2d0',
    messagingSenderId: '838888207729',
    projectId: 'quickserve-194d8',
    storageBucket: 'quickserve-194d8.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASZzmu9ZS_sr30hGrfs8d4E__RdsFMi54',
    appId: '1:838888207729:ios:d0ba194a5d2aade1b7b2d0',
    messagingSenderId: '838888207729',
    projectId: 'quickserve-194d8',
    storageBucket: 'quickserve-194d8.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoTKhoZvyDcNZp9V16EPbf--pvDRrzpyw',
    appId: '1:838888207729:web:19ddd994f6289997b7b2d0',
    messagingSenderId: '838888207729',
    projectId: 'quickserve-194d8',
    authDomain: 'quickserve-194d8.firebaseapp.com',
    storageBucket: 'quickserve-194d8.firebasestorage.app',
    measurementId: 'G-724HT7WD8W',
  );
}
